name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: |
          pod install
          xcodebuild test -project DiaryOfObservation.xcodeproj -scheme DiaryOfObservation -destination 'platform=iOS Simulator,name=iPhone 11 Pro'
